CREATE TABLE CATALOGO (
    PRODUCTO_ID INT PRIMARY KEY,
    PRODUCTO_DESC VARCHAR(255),
    STATUS VARCHAR(50),
    FAMILIA VARCHAR(100)
);

CREATE TABLE REPORTE (
    PRODUCTO_ID INT,
    PRODUCTO_DESC VARCHAR(255),
    VENTA DECIMAL(10, 2),
    UNIDADES INT,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES CATALOGO(PRODUCTO_ID)
);

-- Datos para la tabla CATALOGO
INSERT INTO CATALOGO (PRODUCTO_ID, PRODUCTO_DESC, STATUS, FAMILIA) VALUES
(1, 'Producto A', 'ACTIVO', 'Familia 1');
INSERT INTO CATALOGO (PRODUCTO_ID, PRODUCTO_DESC, STATUS, FAMILIA) VALUES
(2, 'Producto B', 'INACTIVO', 'Familia 2');
INSERT INTO CATALOGO (PRODUCTO_ID, PRODUCTO_DESC, STATUS, FAMILIA) VALUES
(3, 'Producto C', 'ACTIVO', 'Familia 1');
INSERT INTO CATALOGO (PRODUCTO_ID, PRODUCTO_DESC, STATUS, FAMILIA) VALUES
(4, 'Producto D', 'ACTIVO', 'Familia 3');
INSERT INTO CATALOGO (PRODUCTO_ID, PRODUCTO_DESC, STATUS, FAMILIA) VALUES
(5, 'Producto E', 'ACTIVO', 'Familia 2');
INSERT INTO CATALOGO (PRODUCTO_ID, PRODUCTO_DESC, STATUS, FAMILIA) VALUES
(6, 'Producto F', 'INACTIVO', 'Familia 3');
INSERT INTO CATALOGO (PRODUCTO_ID, PRODUCTO_DESC, STATUS, FAMILIA) VALUES
(7, 'Producto G', 'ACTIVO', 'Familia 1');
INSERT INTO CATALOGO (PRODUCTO_ID, PRODUCTO_DESC, STATUS, FAMILIA) VALUES
(8, 'Producto H', 'ACTIVO', 'Familia 2');

-- Datos para la tabla REPORTE
INSERT INTO REPORTE (PRODUCTO_ID, PRODUCTO_DESC, VENTA, UNIDADES) VALUES
(1, 'Producto A', 1500.00, 100);
INSERT INTO REPORTE (PRODUCTO_ID, PRODUCTO_DESC, VENTA, UNIDADES) VALUES
(2, 'Producto B', 2000.00, 150);
INSERT INTO REPORTE (PRODUCTO_ID, PRODUCTO_DESC, VENTA, UNIDADES) VALUES
(3, 'Producto C', 1800.00, 120);
INSERT INTO REPORTE (PRODUCTO_ID, PRODUCTO_DESC, VENTA, UNIDADES) VALUES
(4, 'Producto D', 1700.00, 130);
INSERT INTO REPORTE (PRODUCTO_ID, PRODUCTO_DESC, VENTA, UNIDADES) VALUES
(5, 'Producto E', 1900.00, 110);
INSERT INTO REPORTE (PRODUCTO_ID, PRODUCTO_DESC, VENTA, UNIDADES) VALUES
(6, 'Producto F', 1600.00, 140);
INSERT INTO REPORTE (PRODUCTO_ID, PRODUCTO_DESC, VENTA, UNIDADES) VALUES
(7, 'Producto G', 1550.00, 105);
INSERT INTO REPORTE (PRODUCTO_ID, PRODUCTO_DESC, VENTA, UNIDADES) VALUES
(8, 'Producto H', 1750.00, 125);

-- select nos ayuda aseleccionar las columnas que queremos que aparezcan en la consulta
SELECT 
    C.PRODUCTO_ID, 
    C.PRODUCTO_DESC, 
    C.FAMILIA, 
    R.VENTA, 
    R.UNIDADES
--from nos indica de donde provienen los datos, C es el alias para la tabla Catalogo y R para la tabla reporte    
FROM 
    CATALOGO C
-- realiza la union entre las tablas en base a Producto ID    
JOIN 
    REPORTE R ON C.PRODUCTO_ID = R.PRODUCTO_ID
_--filtro de busqueda para que solo nos aparezcan los elementos con el status de activo     
WHERE 
    C.STATUS = 'ACTIVO';
    